services:
  postgresql:
    image: postgres:15.4
    container_name: game-match-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=gameMatchDB
    ports:
      - 5433:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  app:
    container_name: game-match-app
    depends_on:
      - postgresql
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://postgresql:5432/gameMatchDB"
          }'
    build: .
    ports:
      - 8081:8080
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
