server:
  port: 8080
spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: jdbc:h2:mem:gamematch;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.web-allow-others: true
  jpa:
    properties.javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    properties.hibernate:
      cache.use_second_level_cache: true
      cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      cache.hazelcast.use_native_client: true
      cache.use_minimal_puts: true
      cache.use_query_cache: true
      generate_statistics: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  file.max-history: 5
  file.max-size: 25MB
  level:
    root: info
    org.springframework.web: info
    gr.accepted.gamematch: info
    org.hibernate: info
