server:
  port: 8080
spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: jdbc:h2:mem:gamematch;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.web-allow-others: true
  jpa:
    properties.hibernate:
      generate_statistics: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  file.max-history: 5
  file.max-size: 25MB
  level:
    root: info
    org.springframework.web: info
    gr.accepted.gamematch: info
    org.hibernate: debug
