server:
  servlet.context-path: "/game-match"
spring:
  profiles.active: "@activated-profiles@"
  mvc.servlet.path: "/api"
  application.name: "GameMatch"
springdoc.override-with-generic-response: false

