server:
  port: 8080
spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/changelog-master.xml
  sql:
    init.mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/gameMatchDB
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.web-allow-others: true
  jpa:
    properties.javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    properties.hibernate:
      cache.use_second_level_cache: true
      cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      cache.hazelcast.use_native_client: true
      cache.use_minimal_puts: true
      cache.use_query_cache: true
      generate_statistics: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  file.max-history: 5
  file.max-size: 25MB
  level:
    root: info
    org.springframework.web: info
    gr.accepted.gamematch: info
    org.hibernate: info
